In [ ]:
%matplotlib inline

## What is PyTorch?
Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:
* NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
* 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

### Getting Started

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능합니다.

In [ ]:
from __future__ import print_function
import torch

torch.__version__

'1.12.1+cu113'

초기화되지않은 5x3 행렬을 생성합니다:

In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[9.4204e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


무작위로 초기화된 행렬을 생성합니다:

In [ ]:
x = torch.randn(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)

tensor([[ 1.3382,  0.4777,  0.8953],
        [ 2.1308, -0.7505, -0.0782],
        [ 2.6869, -0.1692, -1.3915],
        [-0.8857, -1.8811,  0.4709],
        [ 1.2157,  1.0768, -0.8049]])
tensor([[0.0893, 0.7360, 0.0614],
        [0.6411, 0.9970, 0.1579],
        [0.2621, 0.3656, 0.4518],
        [0.2640, 0.6851, 0.4568],
        [0.7427, 0.2521, 0.5869]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다:

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로부터 tensor를 직접 생성합니다:

In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.

In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)    # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.4870e-01, -7.4944e-02, -8.5755e-01],
        [-6.6660e-02, -1.0803e-01, -4.2492e-01],
        [-3.7811e-02, -2.4889e-03,  9.6557e-01],
        [ 5.4836e-01,  3.6686e-01, -8.7512e-01],
        [-7.8781e-01,  5.0094e-01,  2.6370e+00]])


행렬의 크기를 구합니다:

In [ ]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


덧셈: 문법1

In [ ]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[ 2.4870e-01, -7.4944e-02, -8.5755e-01],
        [-6.6660e-02, -1.0803e-01, -4.2492e-01],
        [-3.7811e-02, -2.4889e-03,  9.6557e-01],
        [ 5.4836e-01,  3.6686e-01, -8.7512e-01],
        [-7.8781e-01,  5.0094e-01,  2.6370e+00]])
tensor([[9.9605e-02, 7.8829e-01, 7.0393e-04],
        [3.7496e-01, 3.2786e-01, 6.9838e-01],
        [3.1462e-01, 6.8866e-01, 9.6049e-01],
        [7.3804e-01, 5.1684e-01, 3.5912e-01],
        [2.4779e-01, 1.6826e-01, 8.9319e-02]])
tensor([[ 0.3483,  0.7133, -0.8568],
        [ 0.3083,  0.2198,  0.2735],
        [ 0.2768,  0.6862,  1.9261],
        [ 1.2864,  0.8837, -0.5160],
        [-0.5400,  0.6692,  2.7263]])


덧셈: 문법2

In [ ]:
print(torch.add(x, y))

tensor([[ 0.3483,  0.7133, -0.8568],
        [ 0.3083,  0.2198,  0.2735],
        [ 0.2768,  0.6862,  1.9261],
        [ 1.2864,  0.8837, -0.5160],
        [-0.5400,  0.6692,  2.7263]])


덧셈: 결과 tensor를 인자로 제공

In [ ]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[ 9.4206e-35,  0.0000e+00, -8.5684e-01],
        [ 3.0830e-01,  2.1984e-01,  2.7345e-01],
        [ 2.7681e-01,  6.8617e-01,  1.9261e+00],
        [ 1.2864e+00,  8.8370e-01, -5.1600e-01],
        [-5.4001e-01,  6.6920e-01,  2.7263e+00]])
tensor([[ 0.3483,  0.7133, -0.8568],
        [ 0.3083,  0.2198,  0.2735],
        [ 0.2768,  0.6862,  1.9261],
        [ 1.2864,  0.8837, -0.5160],
        [-0.5400,  0.6692,  2.7263]])


덧셈: 바꿔치기(in-place)방식

In [ ]:
# adds x to y
print(y)
y.add_(x)
print(y)

tensor([[9.9605e-02, 7.8829e-01, 7.0393e-04],
        [3.7496e-01, 3.2786e-01, 6.9838e-01],
        [3.1462e-01, 6.8866e-01, 9.6049e-01],
        [7.3804e-01, 5.1684e-01, 3.5912e-01],
        [2.4779e-01, 1.6826e-01, 8.9319e-02]])
tensor([[ 0.3483,  0.7133, -0.8568],
        [ 0.3083,  0.2198,  0.2735],
        [ 0.2768,  0.6862,  1.9261],
        [ 1.2864,  0.8837, -0.5160],
        [-0.5400,  0.6692,  2.7263]])


**Note**

바꿔치기(in-place)방식으로 tensor의 값을 변경하는 연산은 _ 를 접미사로 갖습니다.

예: x.copy_(y), x.t_()는 x 를 변경합니다.

NumPy스러운 인덱싱 표기 방법을 사용할 수도 있습니다!

In [ ]:
print(x)
print(x[:, 1])

tensor([[ 2.4870e-01, -7.4944e-02, -8.5755e-01],
        [-6.6660e-02, -1.0803e-01, -4.2492e-01],
        [-3.7811e-02, -2.4889e-03,  9.6557e-01],
        [ 5.4836e-01,  3.6686e-01, -8.7512e-01],
        [-7.8781e-01,  5.0094e-01,  2.6370e+00]])
tensor([-0.0749, -0.1080, -0.0025,  0.3669,  0.5009])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:

In [ ]:
import torch

x = torch.randn(4, 4)
print(x)

y = x.view(16)
z = y.view(-1, 2)    # the size -1 is inferred from other dimensions
print(y)
print(z)
print(y.size(), z.size())

tensor([[-2.3012, -0.4504, -1.4243,  0.7892],
        [-0.5334,  1.5245,  1.8638,  0.3871],
        [ 0.5468,  0.4732,  0.1630, -1.6833],
        [-0.7740,  1.1296,  0.6939, -0.6215]])
tensor([-2.3012, -0.4504, -1.4243,  0.7892, -0.5334,  1.5245,  1.8638,  0.3871,
         0.5468,  0.4732,  0.1630, -1.6833, -0.7740,  1.1296,  0.6939, -0.6215])
tensor([[-2.3012, -0.4504],
        [-1.4243,  0.7892],
        [-0.5334,  1.5245],
        [ 1.8638,  0.3871],
        [ 0.5468,  0.4732],
        [ 0.1630, -1.6833],
        [-0.7740,  1.1296],
        [ 0.6939, -0.6215]])
torch.Size([16]) torch.Size([8, 2])


만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.

In [ ]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())

tensor([-0.1754])
<class 'torch.Tensor'> <class 'float'>
-0.17535603046417236


읽을 거리:

전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등과 같은 100가지 이상의 Tensor 연산은 <http://pytorch.org/docs/torch> 에 설명되어 있습니다.

### NumPy 변환(Bridge)
Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.
* Torch Tensor를 NumPy 배열로 변환하기

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


* NumPy 배열을 Torch Tensor로 변환하기

NumPy(np) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.

In [ ]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.

### CUDA Tensors

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.

In [ ]:
import torch

# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ''torch.device'' 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.

x = torch.rand(4,4)
if torch.cuda.is_available():
  device = "cuda:0"    # torch.device("cuda:0")    # CUDA 장치 객체(device object)로
  y = torch.ones_like(x, device=device)    # GPU 상에 직접적으로 tensor를 생성하거나
  print(y)


  x = x.to(device)    # ''.to("cuda")'' 를 사용하면 됩니다.
  z = x + y 
  print(z)
  print(z.to("cpu", torch.double))    # ''.to'' 는 dtype도 함께 변경합니다! 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.5506, 1.2256, 1.6839, 1.4287],
        [1.3024, 1.0201, 1.4546, 1.7049],
        [1.6554, 1.0459, 1.8942, 1.3968],
        [1.6957, 1.5947, 1.9944, 1.4799]], device='cuda:0')
tensor([[1.5506, 1.2256, 1.6839, 1.4287],
        [1.3024, 1.0201, 1.4546, 1.7049],
        [1.6554, 1.0459, 1.8942, 1.3968],
        [1.6957, 1.5947, 1.9944, 1.4799]], dtype=torch.float64)


In [ ]:
 x = x.cuda()