<a href="https://colab.research.google.com/github/nijnuyh/AI-DATA/blob/main/1%EA%B0%95_Numpy%EC%9D%98_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## numpy.array

### numpy의 Container.array

In [1]:
import numpy as np 
arr = np.array([1, 2, 3])

arr

array([1, 2, 3])

In [2]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr.shape

(3,)

In [4]:
arr_2d.shape

(3, 3)

## Numpy로 연산하기



### Vector와 Scalar 사이의 연산

벡터의 각 원소에 대해서 연산을 진행

In [5]:
x = np.array([1, 2, 3])
c = 5

print("더하기 : {}".format(x + c))
print("빼기 : {}".format(x - c))
print("곱하기 : {}".format(x * c))
print("나누기 : {}".format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

벡터의 같은 인덱스끼리 연산이 진행!!

In [6]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print("더하기 : {}".format(y + z))
print("빼기 : {}".format( y- z))
print("곱하기 : {}".format(y * z))
print("나누기 : {}".format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


In [7]:
## Array Indexing

### Python의 리스트와 유사하게 진행

In [8]:
W = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

W[0,0]


1

In [9]:
W[2,3]

12

In [10]:
# 7을 가져오려면?

W[1,2]

7

## Array Slicing

Python의 리스트와 유사하게 진행

In [11]:
W = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

#2, 3 -> 행 : 인덱스 0~1 -> [0:2]
#6, 7 -> 열 : 인덱스 1~2 -> [1:3]

W[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [12]:
W[0:2,0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
W[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
W[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
W[0:3,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [16]:
W[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## Array의 Broadcasting

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능  
하지만 만약에 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능합니다.  
이를 **Broadcasting** 이라고 합니다.

### 1. M by N, M by 1

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([0, 1, 0])

x = x[:, None]
print(a+x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


### 2. M by N, 1 by N


In [18]:
y = np.array([0, 1, -1])

print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


### 3. M by N, 1 by N

In [19]:
t = np.array([1, 2, 3]) # 열벡터로 바꿔줘야 함!
t = t[:, None] # Transpose

u = np.array([2, 0, -2])

print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


# III. Numpy로 선형대수 지식 끼얹기

### A. basis

### 영벡터

- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플(, )



In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일행렬

- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)`을 통해 생성, dim은 값, 혹은 튜플(, )

In [22]:
np.ones(2)

array([1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬

- Main Diagonal을 제외한 성분이 0인 행렬
- np.diag((main diagonals))을 통해 생성할 수 있음.

In [24]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [25]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬

- main diagonal == 1인 diagonal matrix(대각 행렬)
- `np.eye(n, (dtype=int, uint, float, complex, ... ))` 를 사용

In [26]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬곱

- 행렬간에 정의되는 곱 연산(dot product)
- 'np.dot()', '@'를 사용

In [28]:
mat_1 = np.array([[1, 4], [2, 3]])
mat_2 = np.array([[7, 9], [0, 6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [29]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

### B. Furthermore

### 트레이스

- Main Diagonal의 sum
- `np.trace()` 을 사용

In [30]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.trace()

15

In [32]:
np.eye(2,dtype=int).trace()

2

### 행렬식

- 행렬을 대표하는 값 중 하나
- 선형변환 과정에서 Vector의 Scaing 척도
- `np.linalg.det()` 으로 계산



In [33]:
arr_2 = np.array([[2, 3],[1, 6]])

arr_2

array([[2, 3],
       [1, 6]])

In [34]:
np.linalg.det(arr_2)

9.000000000000002

In [35]:
arr_3 = np.array([[1, 4, 7],[2, 5, 8],[3, 6, 9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
np.linalg.det(arr_3)

0.0

### 역행렬

- 행렬 A에 대해서 AB = BA = I를 만족하는 행렬 B
- `np.linalg.inv()` 을 사용


In [37]:
mat = np.array([[1, 4],[2, 3]])

mat

array([[1, 4],
       [2, 3]])

In [38]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [39]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

In [40]:
t = np.array([[1, 5, 7],[2, 1, 7],[1, 4, 3]])

t

array([[1, 5, 7],
       [2, 1, 7],
       [1, 4, 3]])

In [41]:
r = np.linalg.inv(t)

r

array([[-0.86206897,  0.44827586,  0.96551724],
       [ 0.03448276, -0.13793103,  0.24137931],
       [ 0.24137931,  0.03448276, -0.31034483]])

In [42]:
r @ t

array([[ 1.00000000e+00,  4.44089210e-16, -1.11022302e-16],
       [-2.77555756e-17,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00, -2.22044605e-16,  1.00000000e+00]])

### 고유값과 고유벡터

- 정방행렬(nxn) A에 대해서 *Ax* = λx 을 만족하는 λ와 x를 각각 고유값과 고유벡터라 한다.
- `np.linald.eig()` 로 계산

In [43]:
mat = np.array([[2, 0, -2],[1, 1, -2],[0, 0, 1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [44]:
np.linalg.eig(mat)

(array([1., 2., 1.]), array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

#### Validation

In [45]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [46]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [47]:
mat @ eig_vec[:, 0]  # Ax

array([0., 1., 0.])

In [48]:
eig_val[0] * eig_vec[:, 0]  # (lambda)x

array([0., 1., 0.])